---
settings:
  name: BlueXP
  platform: cloud
  search: bluexp-relnotes,bluexp-setup-admin,bluexp-cloud-volumes-ontap,bluexp-ontap-onprem,bluexp-azure-netapp-files,bluexp-fsx-ontap,bluexp-cloud-volumes-service-gcp,bluexp-kubernetes,bluexp-remediation,bluexp-backup-recovery,bluexp-copy-sync,bluexp-classification,bluexp-tiering,bluexp-ransomware-protection,bluexp-replication,bluexp-edge-caching,bluexp-cloud-ops,bluexp-automation,cloud-volumes-ontap-relnotes,bluexp-storagegrid,bluexp-e-series,bluexp-s3-storage,bluexp-economic-efficiency,bluexp-operational-resiliency,bluexp-digital-wallet,bluexp-blob-storage,bluexp-reports,bluexp-volume-caching
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 所有BlueXP文件
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: 全部
    tags: all
    class: active
  - title: API
    tags: api
  - title: 連接器與帳戶
    tags: admin
  - title: 擴充功能
    tags: extension
  - title: 治理
    tags: governance
  - title: 健全狀況
    tags: health
  - title: 行動力
    tags: mobility
  - title: 保護
    tags: protection
  - title: 儲存設備
    tags: storage
  tiles:
  - title: 歡迎使用BlueXP
    icon: "./media/icon-docs.png"
    url: concept-overview.html
    summary: 深入瞭解BlueXP的推出。
    tags: all
  - title: 設定與管理
    icon: "./media/icon-admin.png"
    url: https://docs.netapp.com/us-en/bluexp-setup-admin/index.html
    summary: 瞭解如何開始使用BlueXP並管理Connectors、帳戶等。
    tags: all,admin
  - title: 版本資訊
    icon: "./media/icon-docs.png"
    url: https://docs.netapp.com/us-en/bluexp-relnotes/index.html
    summary: 瞭解所有BlueXP的新功能。
    tags: all
  - title: Amazon FSX for NetApp ONTAP 產品
    icon: "./media/icon-fsx.png"
    url: https://docs.netapp.com/us-en/bluexp-fsx-ontap/index.html
    summary: 將ONTAP 完整的功能用作由AWS管理的原生服務。
    tags: all,storage,aws
  - title: Amazon S3儲存設備
    icon: "./media/icon-s3.png"
    url: https://docs.netapp.com/us-en/bluexp-s3-storage/index.html
    summary: 探索及管理AWS帳戶中的Amazon S3儲存區。
    tags: all,storage,aws
  - title: API
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/bluexp-automation/index.html
    summary: 以程式設計方式管理雲端型資源。
    tags: all,api
  - title: Azure Blob 儲存設備
    icon: "./media/icon-azure-blob.png"
    url: https://docs.netapp.com/us-en/bluexp-blob-storage/index.html
    summary: 探索並管理 Azure 訂閱中的 Azure Blob 儲存設備。
    tags: all,storage
  - title: Azure NetApp Files
    icon: "./media/icon-anf.png"
    url: https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html
    summary: 為核心業務應用程式提供高效能檔案儲存服務。
    tags: all,storage,azure
  - title: 備份與還原（ Cloud Backup ）
    icon: "./media/icon-backup.png"
    url: https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html
    summary: 備份及還原雲端和內部部署資料。
    tags: all,aws,azure,gcp,protection
  - title: 分類（ Cloud Data Sense ）
    icon: "./media/icon-data-sense.png"
    url: https://docs.netapp.com/us-en/bluexp-classification/index.html
    summary: 準備好應用程式資料和雲端環境的隱私保護。
    tags: all,governance,aws,azure,gcp
  - title: 雲端運算（運算）
    icon: "./media/icon-compute.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-ops/index.html
    summary: 深入瞭解雲端運算支出、並找出可能的節約效益。
    tags: all,aws,extension
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html
    summary: 讓您的雲端儲存設備更經濟實惠、更聰明、更符合法規要求且更安全。
    tags: all,storage,aws,azure,gcp
  - title: 適用於 Google Cloud Cloud Volumes Service
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-service-gcp/index.html
    summary: 安全、保護及加速您的檔案儲存。
    tags: all,storage,gcp
  - title: 複製與同步（ Cloud Sync ）
    icon: "./media/icon-sync.png"
    url: https://docs.netapp.com/us-en/bluexp-copy-sync/index.html
    summary: 在內部部署與雲端資料儲存區之間同步資料。
    tags: all,aws,azure,gcp,mobility
  - title: 數位顧問（ Active IQ ）
    icon: "./media/icon-activeiq.png"
    url: https://docs.netapp.com/us-en/active-iq/index.html
    tags: all,health
    summary: 可據以行動的情報、達到最佳的儲存健全狀況。
  - title: 數位錢包
    icon: "./media/digital-wallet.png"
    url: https://docs.netapp.com/us-en/bluexp-digital-wallet/index.html
    tags: all,governance
    summary: 管理及監控您的授權與訂閱。
  - title: E系列系統
    icon: "./media/icon-e-series.png"
    url: https://docs.netapp.com/us-en/bluexp-e-series/index.html
    summary: 探索E系列系統、完整檢視混合式多雲端的資料。
    tags: all,storage
  - title: 經濟效益
    icon: "./media/icon-economic-efficiency.png"
    url: https://docs.netapp.com/us-en/bluexp-economic-efficiency/index.html
    summary: 識別目前或預測容量不足的叢集、並實作資料分層或其他容量建議。
    tags: all,governance
  - title: 邊緣快取（全域檔案快取）
    icon: "./media/icon-cache.png"
    url: https://docs.netapp.com/us-en/bluexp-edge-caching/index.html
    summary: 為分散的工作團隊提供即時的全域檔案共用功能。
    tags: all,mobility,aws,azure,gcp
  - title: Kubernetes叢集
    icon: "./media/icon-kubernetes.png"
    url: https://docs.netapp.com/us-en/bluexp-kubernetes/index.html
    summary: 在混合雲中、對Kubernetes叢集進行進階資料管理。
    tags: all,storage,aws,azure
  - title: 移轉報告
    icon: "./media/icon-reports.png"
    url: https://docs.netapp.com/us-en/bluexp-reports/index.html
    summary: 識別儲存環境中的檔案數量、檔案系統樹狀結構的深度和廣度、最大檔案等。
    tags: all,storage
  - title: 內部部署 ONTAP 的叢集
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html
    summary: 使用System Manager和BlueXP的資料服務、從AFF BlueXP管理您的NetApp功能和FAS 功能。
    tags: all,storage
  - title: 營運恢復能力
    icon: "./media/icon-op-resiliency.png"
    url: https://docs.netapp.com/us-en/bluexp-operational-resiliency/index.html
    summary: 實作自動化韌體和軟體組態風險修正、以維持 ONTAP 叢集的健全狀況。
    tags: all,health
  - title: 勒索軟體保護
    icon: "./media/icon-ransomware.png"
    url: https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html
    summary: 評估您的資料對網路攻擊的應變能力。
    tags: all,governance,protection
  - title: 補救（應用程式範本）
    icon: "./media/icon-app-template.png"
    url: https://docs.netapp.com/us-en/bluexp-remediation/index.html
    summary: 自動化BlueXP中的行動、加速資源配置並免除手動工作。
    tags: all,health
  - title: 複寫
    icon: "./media/icon-replication.png"
    url: https://docs.netapp.com/us-en/bluexp-replication/index.html
    summary: 在儲存系統之間複寫資料、以支援備份與災難恢復。
    tags: all,protection
  - title: StorageGRID
    icon: "./media/icon-storagegrid.png"
    url: https://docs.netapp.com/us-en/bluexp-storagegrid/index.html
    summary: 探索StorageGRID 及管理您的系統。
    tags: all,storage
  - title: 分層（雲端分層）
    icon: "./media/icon-tiering.png"
    url: https://docs.netapp.com/us-en/bluexp-tiering/index.html
    summary: 將內部ONTAP 部署的NetApp儲存設備延伸至雲端。
    tags: all,aws,azure,gcp,mobility
  - title: Volume 快取
    icon: "./media/icon-volume-caching.png"
    url: https://docs.netapp.com/us-en/bluexp-volume-caching/index.html
    summary: 建立可寫入的快取磁碟區、以加速資料存取或卸載大量存取磁碟區的流量。
    tags: all,mobility
